[workspace]
members = ["lc-crypto-primitives"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
bytemuck = { version = "1.5.2", features = [
    "min_const_generics",
    "must_cast",
    "zeroable_maybe_uninit",
    "zeroable_atomics",
] }
cfg-match = "0.2.1"
zeroize = { version = "1.3.0" }
libc = { version = "0.2", default-features = false }
concat-idents = "1.1"
