[package]
name = "lc-crypto-primitives"
version.workspace = true
edition.workspace = true

[dependencies]
bytemuck.workspace = true
cfg-match.workspace = true

[features]
alloc = []

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench-asm"
harness = false
src = "bench/bench-asm.rs"
