[package]
name = "lc-crypto-secret"
version.workspace = true
edition.workspace = true

[dependencies]
bytemuck.workspace = true
lc-crypto-primitives.workspace = true

[features]
std = ["alloc"]
alloc = []
nightly-allocator_api = []
nightly-docs = []
